### ISSUE TITLE
Importing CSS and compress not working

### ISSUE THREAD

**Issue by vernak2539** [stevelacy/gulp-stylus#119]
I'm having a little trouble getting stylus to import CSS and minify it at the same time. Compress works correctly when the import is a stylus file, but not CSS

Here is my task.
```js
    gulp.src( '/path/to/files.styl' )
        .pipe( sourcemaps.init() )
        .pipe( stylus({
            compress: true,
            use: nib(),
            "include css": true
         }) )
        .pipe( sourcemaps.write() )
        .pipe( gulp.dest( 'output/path/to/files' ) );
```

**Comment by yckart** [comment]
Same here :'(

**Comment by jenius** [comment]
If it helps at all, I'd suggest using a gulp css minifier rather than trying to compress within stylus. This is a much more solid strategy in the long run. Not entirely sure on this bug though!

**Comment by vernak2539** [comment]
@jenius true, that's what I actually moved to after finding this. Better solution by far

**Comment by stevelacy** [comment]
I will close this now as it seems a solutions was found

**Comment by cjaoude** [comment]
You mean a work around has been found. :) The documentation should at least mention this exception. I just wasted 10min before I noticed the bottom of the file was compressed. The top wasn't because it was a normalize.css import. So it looked like the file was not compressed.

It should be noted in the docs.
