### ISSUE TITLE
Inline Image Option

### ISSUE THREAD

**Issue by zeezali** [stevelacy/gulp-stylus#13]
Is it possible to allow for the inline image option through this task?

Something along the lines of:

```
.pipe(stylus({
    set: ['inline']
}))
```

When I tried the above, it didn't work, but if I run Stylus from the command line using the `--inline` option it works perfectly.

**Comment by Gijsjan** [comment]
I am in the dark. Nothing seems to work of what I try. I would like to use the cli option `--inline` with gulp-stylus.

I have tried:
```
.pipe(stylus(
'inline': true
))
````

**Comment by jenius** [comment]
```js
.pipe(stylus({
   url: 'embedurl',
   'include css': true
))
```

This should be all you need. Set is never necessary with this plugin, anything included as key/val is automatically 'set'. For the url function, I am not aware of what passing through `stylus.url()` would do, nor have I seen this in the stylus docs. You can see the docs for [how to use a custom url function here](https://github.com/jenius/accord/blob/master/docs/stylus.md#url), this is what you should follow. In order to inline images, you need to use a different `url` function, in the example given in the link here, it uses `embedurl` instead in your stylus. This works 100%, and is fully tested and covered.

If you have another use case and can explain it clearly and link me to stylus' docs that describe the feature, I can try to include this functionality as well.

**Comment by honeycider** [comment]
Hello! Forgive my ignorance, but I couldn't get my images inlined after configuring my gulp file following the instructions above. I guess I must be doing it wrong somewhere, and it would be great if you could give me some hints on this, thanks!
```
        .pipe(stylus({
          compress: true,
          error: true,
          use: nib(),
          url: {
            name: 'embedurl',
            paths: [config.srcClientDir + '/img'],
            limit: false
          },
          'include css': true
        }))
```
Also tried
```
        .pipe(stylus({
          compress: true,
          error: true,
          use: nib(),
          url: 'embedurl',
          'include css': true
        }))

```
Results (same for both cases): no image has been included after the compilation, but there were no errors either. The CSS itself has been compiled just like how it was without the options `url` and `include css`

Extras: If this should matter at all, I actually built myself a custom mixin `image-url` for all image urls, as I migrated my project from sass+compass to stylus+nib and tried to convert the functions in a less painful way. Could this be a reason why it did not work?
```
img-path = "/img/"
image-url(filename)
  embedurl(img-path + filename) //changed url() to embedurl()
```

**Comment by andrecavallari** [comment]
Anything?? I cant get this working =(
