### ISSUE TITLE
stylus set

### ISSUE THREAD

**Issue by brunomarcel** [stevelacy/gulp-stylus#8]
Hello, i'm using the stylus .set, it don't work in windows?

<pre>
gulp.task('compress', function () {
    gulp.src('stylus/*.styl')
            .pipe(stylus({set: ['compress']}))
            .pipe(gulp.dest(paths.css));
});
</pre>

**Comment by saumyaj92** [comment]
When I use 'include css': true and 'compress':true together, it doesn't compress the files. I need to use 'include css' because I have two import statements in my stylus file. I want unminified as well as minified versions in my destination folder. Can somebody help me what am I missing? Below is my stylus task:

gulp.task('stylus', function(){
    gulp.src('css/WebHelp.styl')
        .pipe(stylus({
            'include css': true
        }))
        .pipe(rename('AladdinHelp.css'))
        .pipe(gulp.dest('dist/css'));
    gulp.src('css/WebHelp.styl')
        .pipe(stylus({
            'include css': true,
            'compress': true
        }))
        .pipe(rename('AladdinHelp.min.css'))
        .pipe(gulp.dest('dist/css'));
});
